### PR TITLE
ci: use common reviewpad file

### PR DESCRIPTION
**Pull request by marcelosousa**
This pull request uses the Reviewpad common.yml specification to avoid duplication of common workflows across multiple repositories.

This pull request should only be merged after https://github.com/listendev/.github/pull/1.

- [x] I have read the [contributing guidelines](https://github.com/listendev/lstn/blob/main/.github/CONTRIBUTING.md)
- [x] I have made sure that the pull request is of reasonable size and can be easily reviewed

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Hello @marcelosousa, thank you for sending this!

Can you please sign the CLA?

**Comment by marcelosousa** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by marcelosousa** [comment]
recheck

**Comment by marcelosousa** [comment]
@leodido FYI: Reviewpad can be used to trigger GitHub actions with the `triggerWorkflow` built-in ( https://docs.reviewpad.com/guides/built-ins#triggerworkflow). This might be useful to not trigger the CLA assistant on every issue comment. It's of course, a matter of opinion but I really don't like this type of if conditions in GitHub actions (https://github.com/listendev/lstn/blob/main/.github/workflows/cla.yml#L14).

**Review by leodido — APPROVED** [review]

**Comment by leodido** [comment]
> @leodido FYI: Reviewpad can be used to trigger GitHub actions with the `triggerWorkflow` built-in ( https://docs.reviewpad.com/guides/built-ins#triggerworkflow). This might be useful to not trigger the CLA assistant on every issue comment. It's of course, a matter of opinion but I really don't like this type of if conditions in GitHub actions (https://github.com/listendev/lstn/blob/main/.github/workflows/cla.yml#L14).

This would be very cool. Thanks for the suggestion!

Also, feel free to send a PR if you feel so :)

**Pull request merged**
